version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=100GB'
    ports:
      - "9090:9090"
    volumes:
      - /mnt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /mnt/data/prometheus:/prometheus
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    pid: "host"
    network_mode: "host"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped

  ecommerce-exporter:
    image: badjware/ecommerce-exporter:latest
    container_name: ecommerce-exporter
    ports:
      - 9101:8000
    volumes:
      - /mnt/prometheus/ecommerce-exporter.yml:/ecommerce-exporter.yml
    restart: unless-stopped
